Refactor Test1 execution in GitHub Actions workflow
Simplified the test execution command in the workflow.

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,11 +14,12 @@ jobs:
         node-version: '24'
 
     - name: Run Test1
-      run: |
-        output=$(node dist/Test1.js)
-        exit_code=$output
+      run: node dist/Test1.js
+      # run: |
+      #   output=$(node dist/Test1.js)
+      #   exit_code=$output
 
-        if[ $exit_code -ne 0 ]; then
-          echo "error: exit code $exit_code"
-          exit 1
-        fi
+      #   if[ $exit_code -ne 0 ]; then
+      #     echo "error: exit code $exit_code"
+      #     exit 1
+      #   fi
