Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,4 +12,13 @@ jobs:
       uses: actions/setup-node@v2
       with:
         node-version: '24'
-    
+
+    - name: Run Test1
+      run: |
+        output=$(node dist/Test1.js)
+        exit_code=$output
+
+        if[ $exit_code -ne 0 ]; then
+          echo "error: exit code $exit_code"
+          exit 1
+        fi
